const Article = require("../models/articleModel")
var id = Article.createArticle({title:"test",content:"test body"})
if (!id) throw new Error("createArticle failed")
var a = Article.getArticleById(id)
if (!a || a.title !== "test") throw new Error("getArticleById failed")
var all = Article.getAllArticles()
if (!Array.isArray(all) || all.length < 1) throw new Error("getAllArticles failed")
Article.deleteArticle(id)
var gone = Article.getArticleById(id)
if (gone) throw new Error("deleteArticle failed")
console.log("PASS: model.test.js")
